[package]
name = "meshopt"
version = "0.1.0"
authors = ["Graham Wihlidal <graham@wihlidal.ca>"]
description = "Rust ffi bindings and idiomatic wrapper for zeux/meshoptimizer"
homepage = "https://github.com/gwihlidal/meshopt-rs"
repository = "https://github.com/gwihlidal/meshopt-rs"
documentation = "https://docs.rs/meshopt"
readme = "README.md"
keywords = ["rust", "mesh", "optimize", "cache", "3d", "rendering"]
categories = ["rendering", "rendering::engine", ]
license = "MIT"
build = "build.rs"
include = [
    "src/*.rs",
    "build.rs",
    "Cargo.toml",
    "vendor/src/meshoptimizer.h",
    "vendor/src/indexcodec.cpp",
    "vendor/src/indexgenerator.cpp",
    "vendor/src/overdrawanalyzer.cpp",
    "vendor/src/overdrawoptimizer.cpp",
    "vendor/src/simplifier.cpp",
    "vendor/src/stripifier.cpp",
    "vendor/src/vcacheanalyzer.cpp",
    "vendor/src/vcacheoptimizer.cpp",
    "vendor/src/vertexcodec.cpp",
    "vendor/src/vfetchanalyzer.cpp",
    "vendor/src/vfetchoptimizer.cpp",
]

[badges]
travis-ci = { repository = "gwihlidal/meshopt-rs" }
maintenance = { status = "actively-developed" }

[dependencies]
float-cmp = "0.4.0"

[build-dependencies]
cc = { version = "1.0.25", features = ["parallel"] }

[dev-dependencies]
tobj = "0.1.6"
miniz_oxide_c_api = "0.2.0"
rand = "0.5.5"
libc = "0.2.43"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1